metadataId: 51d279f8-e2be-4f5e-9f72-1a53f7535ec1
ogc_feature_api: https://kos-pygeoapi.atkv3-dev.kartverket.cloud/collections
output_directory: produktspesifikasjon
product_slug: grunnkretser
updated: 2025-01-01
