metadataId: 58a262c2-4903-4dea-9490-10065fda6756
ogc_feature_api: https://hybasapi.atgcp1-prod.kartverket.cloud/collections
output_directory: produktspesifikasjon
product_slug: dybdedata
updated: 2025-10-31
